/* jetlunJetlunHanService.h
   Generated by gSOAP 2.7.9i from JetlunHan.hpp
   Copyright(C) 2000-2007, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#ifndef jetlunJetlunHanService_H
#define jetlunJetlunHanService_H
#include "jetlunH.h"

namespace jetlun {
class SOAP_CMAC JetlunHanService : public soap
{ public:
		JetlunHanService();
		JetlunHanService(soap_mode iomode);
		JetlunHanService(soap_mode imode, soap_mode omode);
	virtual ~JetlunHanService();
	virtual	void JetlunHanService_init(soap_mode imode, soap_mode omode);
	virtual	JetlunHanService *copy();
	virtual	int bind(const char *host, int port, int backlog);
	virtual	int accept();
	virtual	int serve();
	virtual	int dispatch();
	// Service operations (you should define these):
	/// Web service method 'startGwModule':
	virtual	int startGwModule(hs__StartGwModuleRequest request, hs__NoResponse &response);
	/// Web service method 'getGwModuleStatus':
	virtual	int getGwModuleStatus(int &response);
};

} // namespace jetlun

#endif
