/* jetlunJetlunHanProxy.h
   Generated by gSOAP 2.7.9i from JetlunHan.hpp
   Copyright(C) 2000-2007, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#ifndef jetlunJetlunHanProxy_H
#define jetlunJetlunHanProxy_H
#include "jetlunH.h"

namespace jetlun {

class SOAP_CMAC JetlunHanProxy : public soap
{ public:
		/// endpoint URL (set to override)
		const char *soap_endpoint;
		JetlunHanProxy();
		JetlunHanProxy(soap_mode iomode);
		JetlunHanProxy(soap_mode imode, soap_mode omode);
	virtual	~JetlunHanProxy();
	virtual	void JetlunHanProxy_init(soap_mode imode, soap_mode omode);
	/// Disable/remove SOAP Header from message
	virtual	void soap_noheader();
	/// Get SOAP Fault structure (NULL when absent)
	virtual	const SOAP_ENV__Fault *soap_fault();
	/// Get SOAP Fault string (NULL when absent)
	virtual	const char *soap_fault_string();
	/// Get SOAP Fault detail as string (NULL when absent)
	virtual	const char *soap_fault_detail();
	/// Web service method 'startGwModule':
	virtual	int startGwModule(hs__StartGwModuleRequest request, hs__NoResponse &response);
	/// Web service method 'getGwModuleStatus':
	virtual	int getGwModuleStatus(int &response);
};

} // namespace jetlun

#endif
