#!/bin/sh


sample_cpu_time()
{
	#sample=$(cut -f 14,15 -d ' ' /proc/$1/stat 2>&1 /dev/null)
	sample=$(cut -f 14,15 -d ' ' /proc/6120/stat 2>&1 /dev/null)
	if [ $? -ne 0 ]; then
		return 1	
	fi
	echo $sample
	return 0	
}


echo "running $app"
sample_cpu_time		
sample_cpu_time		
sample_cpu_time		
sample_cpu_time		
sample_cpu_time		
sample_cpu_time		
sample_cpu_time		
sample_cpu_time		
sample_cpu_time		
sample_cpu_time		
sample_cpu_time		
sample_cpu_time		
sample_cpu_time		

	
