/* policynetcaPolicyNetCAService.cpp
   Generated by gSOAP 2.7.9i from csr.hpp
   Copyright(C) 2000-2007, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#include "policynetcaPolicyNetCAService.h"

namespace policynetca {

PolicyNetCAService::PolicyNetCAService()
{	PolicyNetCAService_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
}

PolicyNetCAService::PolicyNetCAService(soap_mode iomode)
{	PolicyNetCAService_init(iomode, iomode);
}

PolicyNetCAService::PolicyNetCAService(soap_mode imode, soap_mode omode)
{	PolicyNetCAService_init(imode, omode);
}

PolicyNetCAService::~PolicyNetCAService()
{ }

void PolicyNetCAService::PolicyNetCAService_init(soap_mode imode, soap_mode omode)
{	static const struct Namespace namespaces[] =
{
	{"SOAP-ENV", "http://www.w3.org/2003/05/soap-envelope", "http://www.w3.org/2003/05/soap-envelope", NULL},
	{"SOAP-ENC", "http://www.w3.org/2003/05/soap-encoding", "http://www.w3.org/2003/05/soap-encoding", NULL},
	{"xsi", "http://www.w3.org/2001/XMLSchema-instance", "http://www.w3.org/*/XMLSchema-instance", NULL},
	{"xsd", "http://www.w3.org/2001/XMLSchema", "http://www.w3.org/*/XMLSchema", NULL},
	{"xop", "http://www.w3.org/2004/08/xop/include", NULL, NULL},
	{"xmime5", "http://www.w3.org/2005/05/xmlmime", NULL, NULL},
	{"policynet", "urn:policynet/0.0.0", NULL, NULL},
	{NULL, NULL, NULL, NULL}
};
	soap_imode(this, imode);
	soap_omode(this, omode);
	this->namespaces = namespaces;
};

PolicyNetCAService *PolicyNetCAService::copy()
{	PolicyNetCAService *dup = new PolicyNetCAService();
	soap_copy_context(dup, this);
	return dup;
}

int PolicyNetCAService::bind(const char *host, int port, int backlog)
{	return soap_bind(this, host, port, backlog);
}

int PolicyNetCAService::accept()
{	return soap_accept(this);
}

int PolicyNetCAService::serve()
{
#ifndef WITH_FASTCGI
	unsigned int k = this->max_keep_alive;
#endif
	do
	{	soap_begin(this);
#ifdef WITH_FASTCGI
		if (FCGI_Accept() < 0)
		{
			this->error = SOAP_EOF;
			return soap_send_fault(this);
		}
#endif

		soap_begin(this);

#ifndef WITH_FASTCGI
		if (this->max_keep_alive > 0 && !--k)
			this->keep_alive = 0;
#endif

		if (soap_begin_recv(this))
		{	if (this->error < SOAP_STOP)
			{
#ifdef WITH_FASTCGI
				soap_send_fault(this);
#else 
				return soap_send_fault(this);
#endif
			}
			soap_closesock(this);

			continue;
		}

		if (soap_envelope_begin_in(this)
		 || soap_recv_header(this)
		 || soap_body_begin_in(this)
		 || dispatch() || (this->fserveloop && this->fserveloop(this)))
		{
#ifdef WITH_FASTCGI
			soap_send_fault(this);
#else
			return soap_send_fault(this);
#endif
		}

#ifdef WITH_FASTCGI
		soap_destroy(this);
		soap_end(this);
	} while (1);
#else
	} while (this->keep_alive);
#endif
	return SOAP_OK;
}

static int serve_policynet__CertificateSigningRequest(PolicyNetCAService*);
static int serve_policynet__CertificateConfirmRequest(PolicyNetCAService*);
static int serve_policynet__CertificateRevocationRequest(PolicyNetCAService*);
static int serve_policynet__CertificateRevocationListRequest(PolicyNetCAService*);

int PolicyNetCAService::dispatch()
{	if (soap_peek_element(this))
		return this->error;
	if (!soap_match_tag(this, this->tag, "policynet:CertificateSigningRequest"))
		return serve_policynet__CertificateSigningRequest(this);
	if (!soap_match_tag(this, this->tag, "policynet:CertificateConfirmRequest"))
		return serve_policynet__CertificateConfirmRequest(this);
	if (!soap_match_tag(this, this->tag, "policynet:CertificateRevocationRequest"))
		return serve_policynet__CertificateRevocationRequest(this);
	if (!soap_match_tag(this, this->tag, "policynet:CertificateRevocationListRequest"))
		return serve_policynet__CertificateRevocationListRequest(this);
	return this->error = SOAP_NO_METHOD;
}

static int serve_policynet__CertificateSigningRequest(PolicyNetCAService *soap)
{	struct policynet__CertificateSigningRequest soap_tmp_policynet__CertificateSigningRequest;
	policynet__CertificateSigningResponse Response;
	Response.soap_default(soap);
	soap_default_policynet__CertificateSigningRequest(soap, &soap_tmp_policynet__CertificateSigningRequest);
	soap->encodingStyle = NULL;
	if (!soap_get_policynet__CertificateSigningRequest(soap, &soap_tmp_policynet__CertificateSigningRequest, "policynet:CertificateSigningRequest", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = soap->CertificateSigningRequest(soap_tmp_policynet__CertificateSigningRequest.Request, Response);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	Response.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || Response.soap_put(soap, "policynet:CertificateSigningResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || Response.soap_put(soap, "policynet:CertificateSigningResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

static int serve_policynet__CertificateConfirmRequest(PolicyNetCAService *soap)
{	struct policynet__CertificateConfirmRequest soap_tmp_policynet__CertificateConfirmRequest;
	policynet__CertificateConfirmResponse Response;
	Response.soap_default(soap);
	soap_default_policynet__CertificateConfirmRequest(soap, &soap_tmp_policynet__CertificateConfirmRequest);
	soap->encodingStyle = NULL;
	if (!soap_get_policynet__CertificateConfirmRequest(soap, &soap_tmp_policynet__CertificateConfirmRequest, "policynet:CertificateConfirmRequest", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = soap->CertificateConfirmRequest(soap_tmp_policynet__CertificateConfirmRequest.Confirm, Response);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	Response.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || Response.soap_put(soap, "policynet:CertificateConfirmResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || Response.soap_put(soap, "policynet:CertificateConfirmResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

static int serve_policynet__CertificateRevocationRequest(PolicyNetCAService *soap)
{	struct policynet__CertificateRevocationRequest soap_tmp_policynet__CertificateRevocationRequest;
	policynet__CertificateRevocationResponse Response;
	Response.soap_default(soap);
	soap_default_policynet__CertificateRevocationRequest(soap, &soap_tmp_policynet__CertificateRevocationRequest);
	soap->encodingStyle = NULL;
	if (!soap_get_policynet__CertificateRevocationRequest(soap, &soap_tmp_policynet__CertificateRevocationRequest, "policynet:CertificateRevocationRequest", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = soap->CertificateRevocationRequest(soap_tmp_policynet__CertificateRevocationRequest.SenderCertificate, soap_tmp_policynet__CertificateRevocationRequest.CertRev, Response);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	Response.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || Response.soap_put(soap, "policynet:CertificateRevocationResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || Response.soap_put(soap, "policynet:CertificateRevocationResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

static int serve_policynet__CertificateRevocationListRequest(PolicyNetCAService *soap)
{	struct policynet__CertificateRevocationListRequest soap_tmp_policynet__CertificateRevocationListRequest;
	policynet__CertificateRevocationListResponse Response;
	Response.soap_default(soap);
	soap_default_policynet__CertificateRevocationListRequest(soap, &soap_tmp_policynet__CertificateRevocationListRequest);
	soap->encodingStyle = NULL;
	if (!soap_get_policynet__CertificateRevocationListRequest(soap, &soap_tmp_policynet__CertificateRevocationListRequest, "policynet:CertificateRevocationListRequest", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = soap->CertificateRevocationListRequest(soap_tmp_policynet__CertificateRevocationListRequest._param_1, Response);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	Response.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || Response.soap_put(soap, "policynet:CertificateRevocationListResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || Response.soap_put(soap, "policynet:CertificateRevocationListResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

} // namespace policynetca

/* End of server object code */
